// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WearMe.Data.Models;

namespace WearMe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190821154334_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WearMe.Data.Models.Category", b =>
                {
                    b.Property<int>("CategoryId");

                    b.Property<string>("CategoryName");

                    b.Property<string>("Desciption");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WearMe.Data.Models.Cloth", b =>
                {
                    b.Property<int>("ClothId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<string>("ImageThumbnailUrl");

                    b.Property<string>("ImageUrl");

                    b.Property<bool>("InStock");

                    b.Property<bool>("IsTrending");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<int>("SexId");

                    b.Property<int>("Size");

                    b.HasKey("ClothId");

                    b.HasIndex("CategoryId", "SexId");

                    b.ToTable("Clothes");
                });

            modelBuilder.Entity("WearMe.Data.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("AddressLine2");

                    b.Property<string>("City")
                        .HasMaxLength(10);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("OrderPlaced");

                    b.Property<decimal>("OrderTotal");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("State")
                        .HasMaxLength(10);

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WearMe.Data.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int>("ClothId");

                    b.Property<int>("OrderId");

                    b.Property<decimal>("Price");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("ClothId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("WearMe.Data.Models.Sex", b =>
                {
                    b.Property<int>("SexId");

                    b.Property<string>("SexGroup");

                    b.HasKey("SexId");

                    b.ToTable("SexGroups");
                });

            modelBuilder.Entity("WearMe.Data.Models.SexCategory", b =>
                {
                    b.Property<int>("CategoryId");

                    b.Property<int>("SexId");

                    b.Property<int>("SexCategoryId");

                    b.HasKey("CategoryId", "SexId");

                    b.HasIndex("SexId");

                    b.ToTable("SexCategories");
                });

            modelBuilder.Entity("WearMe.Data.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<int?>("ClothId");

                    b.Property<string>("ShoppingCartId");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ClothId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("WearMe.Data.Models.Cloth", b =>
                {
                    b.HasOne("WearMe.Data.Models.SexCategory", "SexCategory")
                        .WithMany("Cloths")
                        .HasForeignKey("CategoryId", "SexId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WearMe.Data.Models.OrderDetail", b =>
                {
                    b.HasOne("WearMe.Data.Models.Cloth", "Cloth")
                        .WithMany()
                        .HasForeignKey("ClothId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WearMe.Data.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WearMe.Data.Models.SexCategory", b =>
                {
                    b.HasOne("WearMe.Data.Models.Category", "Category")
                        .WithMany("SexCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WearMe.Data.Models.Sex", "Sex")
                        .WithMany("SexCategories")
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WearMe.Data.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("WearMe.Data.Models.Cloth", "Cloth")
                        .WithMany()
                        .HasForeignKey("ClothId");
                });
#pragma warning restore 612, 618
        }
    }
}
